### ISSUE TITLE
Multiple extra-vars are not supported in playbook action

### ISSUE THREAD

**Issue by chris-downs** [StackStorm-Exchange/stackstorm-ansible#1]
From the ansible command line it is possible to specify multiple `extra-vars` by including multiple `-e\--extra-vars` arguments when running a playbook. 

Example:
```ansible-playbook playbook.yml -e @path_to_file_with_vars.yaml|json -e key1=value1 -e key2=value2```

Currently only a single extra-vars entry is supported. I was able to work around this limitation using the following hack to the `AnsibleBaseRunner` class:
```
class AnsibleBaseRunner(object):
    """
    Base class for all Ansible Runners
    """
...
    def __init__(self, args):
        """
        :param args: Input command line arguments
        :type args: ``list``
        """
        self.args = args[1:]
        for i, arg in enumerate(self.args):
            if '--extra_vars' in arg:
                for var in arg.split("--extra_vars=")[1].split(','):
                    self.args.append("-e {0}".format(var))
                del self.args[i]
                break
        self._prepend_venv_path()
```
This allows you to comma separate a list of extra-vars which are then appended to the list of args passed to ansible.

Obviously there are cleaner ways to do this. From a UX perspective I'd love to see the extra_vars parameter turned into a list similar to how `env` works (with a list of strings instead of a dict since you can pass both file paths and k\v pairs). That makes it clear to the user that multiple extra_vars can be used and also will make it easier to iterate under the hood to add multiple arguments. It also looks cleaner than comma separation when reading through a workflow. 

Example inside of a mistral workflow:
```
ansible.deploy.service:
  input:
    - project
    - playbook_dir
  tasks:
    create_image:
      # [300, 50]
      action: ansible.playbook
      input:
        cwd: "{{ _.playbook_dir }}"
        playbook: playbook.yml
        extra_vars: 
            - "@vars/gce-{{ _.project }}/test_service.yml"
            - "service_image_name=test-image-201704111529"
        inventory_file: "{{ _.playbook_dir }}/inventory/gce-{{ _.project }}/"
        env:
          ANSIBLE_CONFIG: ansible-gce-{{ _.project }}.cfg
          GCE_PROJECT: gce-{{ _.project }}
...
```

Let me know if you have any questions!
