### ISSUE TITLE
In playbook.yaml, support `vault_password`

### ISSUE THREAD

**Issue by djha-skin** [StackStorm-Exchange/stackstorm-ansible#29]
This issue is a feature request.

When I call the `ansible.playbook` command, I want to be able to specify the vault password without using a vault password file. That way, I can set the vault password in the stackstorm key/value store and use it from a rule like this like this:

```
action:
    ref: "ansible.playbook"
    parameters:
        playbook: "playbook.yaml"
        vault_password: "{{ st2kv.system.vault_password }}"
```
