### ISSUE TITLE
Pass the parameter '-i' to ansible playbooks

### ISSUE THREAD

**Issue by rgrueebler** [StackStorm-Exchange/stackstorm-ansible#32]
Hi everyone,

Is it possible to use the option '-i' on an ansible playbook? I want to achieve that I can run a stackstorm action from the UI and pass an IP address to it. So I would be able to run a playbook without adding hosts to the ansible inventory file.
The user doesn't have do be worried about ansible. They could add an ip address on the stackstorm UI an runthe action without knowing that ansible is called in the background.

Thank you
Remo

**Comment by nmaludy** [comment]
@rgrueebler normal ansible behavior on the command line allows you to specify your inventory directly on the CLI using the `-i` flag as either a list of hosts or a file.

The `ansible.playbook` action already has this functionality using the `inventory_file` parameter. When specifying a list of hosts with Ansible, it is kind of broken in that you need a trailing comma, so you would specify on the CLI like `-i 192.168.1.10,`. Same is true for using the `inventory_file` parameter:

```
  run_ansible:
    action: ansible.playbook
    input:
        playbook: '/etc/ansible/playbooks/blah.yaml'
        inventory_file: "192.168.1.10,"
```
