### ISSUE TITLE
Support pack config

### ISSUE THREAD

**Issue by nicholasamorim** [StackStorm-Exchange/stackstorm-ansible#42]
Would it make sense to have certain things as pack config? Very much like `ansible.cfg` in a way.

The config could set variables that are commonly used across all runs such as:

`private_key`
`inventory_file`
and some global `env` values if need be.

**Comment by punkrokk** [comment]
Can you expand on this thinking @nicholasamorim. I think I know where you are going with this as I have some of this in a fork, but if you could define your requirements in a more complete way it will help everyone hone in on a path forward. 

Btw - wouldn't one wish to store things like a private_key in an encrypted datastore value?

**Comment by nicholasamorim** [comment]
Well, in my specific case, I had to set:

`ANSIBLE_SSH_USER` to stanley using the `env` and set the `private_key` as well as `cwd` every time I use `ansible.playbook`.

I know that this stuff can be circumvented by using env vars as well as abstracting the `ansible.playbook` behind a ST2 workflow.

But I just think it would be nice to provide a set of defaults in `/opt/stackstorm/configs/ansible.yaml` so that every action would run with them by default. If this would support retrieving from the KV even better.

`cwd` is a pretty clear case as a lot of people tend to have their playbooks in a single repo/folder in the filesystem.

So an example:

```yaml
cwd: "/path/to/my/plays"
inventory_file: "envs/{{ st2kv('system.ENV') }}/hosts"
private_key: "/home/stanley/.ssh/stanley_rsa"
env:
   ANSIBLE_SSH_USER: stanley
   ANOTHER_DEFAULT_ENV_VAR: myvalue
```

So these would always be used unless overriden at the action level.

Does that make sense?
