### ISSUE TITLE
support json in extra_vars

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm-Exchange/stackstorm-ansible#6]
If I'm reading [this](https://github.com/StackStorm-Exchange/stackstorm-ansible/blob/master/actions/lib/ansible_base.py#L58-L61) right, ansible.playbook doesn't support anything other than files and var=value definitions, not inline yaml or inline json, right? 

According to [the ansible docs](http://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line), `--extra-vars` supports inline json (>=v1.2) and inline yaml (>=v1.3). (of course json is yaml, so only bother with json). Could this be enhanced to support that as well?

I'm using a playbook in an action chain, and I would like to pass in yaml like this:
```yaml
---
chain:
  -
    name: "my_great_action_chain_action"
    ref: "ansible.playbook"
    parameters:
      playbook: "playbooks/cool.yaml"
      extra_vars:
        -
          important_var_name:
            - { name: '{{ var_from_earlier_action }}', otherkey: '{{ var_from_earlier_action }}' }
```

This would approximate how I would add the vars if I added them directly to the playbook under vars.
